### ISSUE TITLE
No unitypackage available ?

### ISSUE THREAD

**Issue by mickev36** [Chykary/FizzyFacepunch#1]
Hi,

In the README, it is specified a unitypackage is available. Unfortunately, none are available on the release page. 

Possible solutions : 
- Put a unitypackage on the releases
- Put a disclaimer to copy manually the sources inside a Mirror Transport directory

Have a great day, thanks for your work !

**Comment by Chykary** [comment]
Hello! There is no release yet because the transport is not finished. I will release it with a package next week or so. :-)

**Comment by mickev36** [comment]
Really great news ! :-) Looking forward to that

**Comment by mickev36** [comment]
Hi,

Just checking in, do you have an ETA for a first release ? Don't want to pressure you at all, I just would like to know if I should wait or switch to FizzySteamworks/Steamworks.NET (and forget about using Facepunch.steamworks entierely, which would be really inconvenient :-( )

Or maybe there's a way to use both Steamworks.NET as a transport, + Facepunch.steamworks for the Steam general API ? Tried, but it seems confilcts emerge when both are installed.

Again, thanks a lot for your work, really, it's awesome.

**Comment by Chykary** [comment]
Hello,

sorry for the delay! Just fixed the remaining bugs and released a package.

**Comment by mickev36** [comment]
Again, thanks a lot ! I'll be the first buyer of your game :-)
