### ISSUE TITLE
NetCommon.MAX_MESSAGES value of 1024 triggers exception in Facepunch.Steamworks because it's out of the defined range of [1..256]

### ISSUE THREAD

**Issue by jasedeacon** [Chykary/FizzyFacepunch#11]
NextClient.ReceiveData and NextServer.ReceiveData both call ConnectionManager.Receive with a value which is too large, which triggers this exception: https://github.com/Facepunch/Facepunch.Steamworks/blob/1bae58560200c74fe53beeddb382aea4d83615f1/Facepunch.Steamworks/Networking/ConnectionManager.cs#L113 and causes connections to fail.

Changing MAX_MESSAGES to be within the specified range (E.g. 256) results in no errors and a connection being established successfully.

**Comment by Chykary** [comment]
Good find, thank you!
