### ISSUE TITLE
ClientSend and ServerSend signature error

### ISSUE THREAD

**Issue by mickev36** [Chykary/FizzyFacepunch#22]
Hello,

When importing this package with Mirror 53, compilations errors appear (FizzyFacepunch not properly overriding ClientSend and ServerSend Methods)

Are you planning on keeping this module up-to-date with Mirror ? Or should I use Steamworks.NET instead ?

Many Thanks

**Comment by hhvmw** [comment]
@mickev36 Check out the latest pull request. You can fix the issue quite easily just by swapping parameters yourself, which is what I did.

**Comment by barsovya** [comment]
Lol, there's just a need to swap arguments. Who thought of making such changes to the repository?

**Comment by LukeSeers** [comment]
I wouldn't say it's no longer supported, but more like slower compared to https://github.com/Chykary/FizzySteamworks updates. I've lightly tested the latest master branch, and it seems to be working fine with the latest mirror version.

**Comment by 1iryu** [comment]
@barsovya 
Can you tell me what to do?
I'm struggling for the same reason as the poster

**Comment by LukeSeers** [comment]
@1iryu Have you tried the latest master branch?

**Comment by 1iryu** [comment]
@LukeSeers  
I setted up with "FizzyFacepunch-4.3.unitypackage" for unity (https://github.com/Chykary/FizzyFacepunch/releases/tag/v4.3)
Is this not so good?

**Comment by LukeSeers** [comment]
That's not the master branch, that is a release. The master branch is this https://github.com/Chykary/FizzyFacepunch

**Comment by 1iryu** [comment]
I followed README of this repository
I got an error after installing the unity package according to this method, so I copied the master branch here to a specific location, but I still get the error (although the error has decreased a bit).


**environment**
mirror v57
unity NET4.0
facepunch (https://www.youtube.com/watch?v=72cRiBkUZbY       <-- I setted up with the way)

**Error sentence**
"Assets\Mirror\Runtime\Transport\FizzyFacepunch\LegacyCommon.cs(54,38): error CS0117: 'P2PSessionError' does not contain a definition for 'NotRunningApp'"
"Assets\Mirror\Runtime\Transport\FizzyFacepunch\LegacyCommon.cs(54,38): error CS0117: 'P2PSessionError' does not contain a definition for 'NotRunningApp'"

**Comment by LukeSeers** [comment]
I'm sorry, but I don't want this turning into text support. If your stuck you should join the community mirror discord and ask there.

But, anyway it says "NotRunningApp" meaning that you haven't Initialized the steam client. To tell if you have Initialized the steam client, you'll see that you'll be playing a game on your steam account or you might have given it the wrong steam AppID.

**Comment by 1iryu** [comment]
@LukeSeers  "But, anyway it says "NotRunningApp" meaning that you haven't Initialized the steam client. To tell if you have Initialized the steam client, you'll see that you'll be playing a game on your steam account or you might have given it the wrong steam AppID."

I need to run a script to set this, but I'm getting an error so I can't run it

also What are other people using instead of Mirror?

**Comment by 1iryu** [comment]
@LukeSeers 
![image](https://user-images.githubusercontent.com/93420248/151651986-67140183-3c42-4bc1-a651-e763387a9497.png)

The "setting up" in this repository also says "and copy it to the Assets / Mirror / Runtime / Transports / FizzyFacepunch folder in your Unity project".

So I thought the mirror is the basic network solution

**Comment by LukeSeers** [comment]
This issue should have now been fixed from: https://github.com/Chykary/FizzyFacepunch/pull/23 there has not been a release as of yet so, to get the latest fixes please just replaces the files with the latest master branch: https://github.com/Chykary/FizzySteamworks
