### ISSUE TITLE
How to choose SteamSockets?

### ISSUE THREAD

**Issue by marcospgp** [Chykary/FizzyFacepunch#29]
> FizzyFacepunch brings together [Steam](https://store.steampowered.com/) and [Mirror](https://github.com/vis2k/Mirror) . It supports both the old SteamNetworking as well as the new SteamSockets.

How can I ensure the newer sockets are used in order to avoid IPs from being made public (as happened to Dani with Crab Game)?

**Comment by LukeSeers** [comment]
As stated here: https://github.com/Facepunch/Facepunch.Steamworks/issues/643#issuecomment-1061683592 you would want to use the newer SteamSockets. FizzyFacepunch uses the newer SteamSockets by default anyway `UseNextGenSteamNetworking = true; `. If you uncheck it then it would fallback to use the older one and thus show their IP.

Long story short just set `UseNextGenSteamNetworking` to `true` and your fine.

https://github.com/Chykary/FizzyFacepunch/blob/8136d0ea5ebac77d94adf8e364fd789072baa7c5/FizzyFacepunch.cs#L27-L28
