### ISSUE TITLE
Server List

### ISSUE THREAD

**Issue by xxCody** [Chykary/FizzyFacepunch#4]
Is there a way to implement a server list with this?  Does this automatically use Steam's built in server list?

**Comment by EmreBugday99** [comment]
Directly from the FacePunch's GitHub page... I am going to suggest you to search before submitting issues...

```cs
using ( var list = new ServerList.Internet() )
{
    list.AddFilter( "map", "de_dust" );
    await list.RunQueryAsync();

    foreach ( var server in list.Responsive )
    {
        Console.WriteLine( $"{server.Address} {server.Name}" );
    }
}
```

**Comment by Chykary** [comment]
This is a FacePunch issue, not a transport issue. :)
