### ISSUE TITLE
FizzyFacepunch could not initialise: SteamAPI_SteamNetworkingSockets_v008

### ISSUE THREAD

**Issue by LoneSurvivor82** [Chykary/FizzyFacepunch#5]
Hi,

I did all the steps you wrote on the start page but if I start the game in Unity, I get this exception:

FizzyFacepunch could not initialise: SteamAPI_SteamNetworkingSockets_v008
UnityEngine.Debug:LogError(Object)
Mirror.FizzySteam.FizzyFacepunch:Awake() (at Assets/Mirror/Runtime/Transport/FizzyFacepunch/FizzyFacepunch.cs:43)

It doesn't matter if I add 480 as SteamAppID or the SteamID from my own game.

Do you have any idea?

**Comment by takeNoC** [comment]
Try clean installation and make sure are is running and you are signed in

**Comment by Chykary** [comment]
That's a FacePunch issue, not a transport issue. However, as takeNoC mentioned, doing a fresh import of assets and clean install often works wonders.
