### ISSUE TITLE
Cannot ban or kick

### ISSUE THREAD

**Issue by takeNoC** [Chykary/FizzyFacepunch#6]
Hello,

How to ban or kick someone from a lobby?
If it's not available could someone help me coding it myself from steamWorks.net?

**Comment by Chykary** [comment]
If you mean kick from SteamLobby, you need to send a Steam Chat Message and make the client disconnect itself. However, that is not transport related.

Kicking/Banning from Mirror works as with any other transport - the host can close the connection .

**Comment by takeNoC** [comment]
@Chykary hey but if I'm kick people out by asking them to disconnect from their side, that means there is a room for hacking there.
They could still be connected as long as the room is still up.

Is there is any backend way to force them out of the lobby or ban them ?

**Comment by Chykary** [comment]
It's weird but currently, Steam does not seem to have another way of removing people from the lobby. See https://partner.steamgames.com/doc/api/ISteamMatchmaking 
"
LobbyKicked_t
Currently unused! If you want to implement kicking at this time then do it with a special packet sent with SendLobbyChatMsg, when the user gets the packet they should call LeaveLobby."
